import type { Metadata } from "next";
import "./globals.css";
import BgSpotlight from "@/components/BgSpotlight";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "awahabt | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <BgSpotlight />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
