import type { Metadata } from "next";
import "./globals.css";
import BgSpotlight from "@/components/BgSpotlight";


export const metadata: Metadata = {
  title: "awahabt | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased text-black dark:text-white dark:bg-black-100`}>
        <BgSpotlight />
        {children}
      </body>
    </html>
  );
}
